name: csxx46-ay2526s2-mini-project
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.13
  - pip
  - numpy==2.3.0
  - pandas==2.3.0
  - scikit-learn==1.7.0
  - matplotlib==3.10
  - pillow==11.2.1
  - scipy==1.15.2
  - sympy==1.14.0
  - joblib==1.5.1
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cpu
      - torch==2.7.0
      - torchvision==0.22.0
      - minigrid==3.0.0
      - gymnasium==1.2.1
